apiVersion: v1
kind: Service
metadata:
  name: vitai-front-nodeport
  namespace: vitai
spec:
  type: NodePort
  selector:
    app: vitai-front
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
