apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vitai-pvc
  namespace: vitai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
