apiVersion: v1
kind: Service
metadata:
  name: vitai-front-service
  namespace: vitai
spec:
  type: ClusterIP
  selector:
    app: vitai-front
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
